import { doc, getDoc } from "firebase/firestore";
import { db } from "./firebase";

// Loads the static peaks snapshot generated by scripts/export_peaks.py
export async function fetchPeaks() {
  // "/peaks.json" is served from the "public" folder by Vite
  const response = await fetch("/peaks.json");

  // fetch does not throw on HTTP errors, so we check manually
  if (!response.ok) {
    throw new Error(`Cannot load peaks (HTTP ${response.status})`);
  }

  return response.json();
}

export async function fetchPeakDetails(peakId) {
  const snap = await getDoc(doc(db, "peaks", peakId));
  // exists() is false if the document is missing
  return snap.exists() ? snap.data() : null;
}